           
            h=figure; 
            %plot(relocations);  % over hosts,then services
            [f,x] = ecdf(relocations1);  plot(x,f,'r'); hold on;
            [f,x] = ecdf(relocations2);  plot(x,f,'--b'); 
            axis([0 20 0 1]);
            hXLabel=xlabel('Relocation per Step'); 
            hYLabel=ylabel('Cumulative Probablity'); 
            set( gca                       , ...
                'FontName'   , 'Times New Roman' );
            set([hXLabel, hYLabel], ...
                'FontName'   , 'Times New Roman');
            set([hXLabel, hYLabel]  , ...
                'FontSize'   , 24          );
              set(gca, ...
              'Box'         , 'off'     , ...
              'TickDir'     , 'out'     , ...
              'TickLength'  , [.02 .02] , ...
              'XMinorTick'  , 'on'      , ...
              'YMinorTick'  , 'on'      , ...
              'XGrid'       , 'on'      , ...              
              'YGrid'       , 'on'      , ...
              'XColor'      , [.3 .3 .3], ...
              'YColor'      , [.3 .3 .3], ...
              'XTick'       , 0:10:100, ...
              'LineWidth'   , 2         ,...
              'YTick'       , 0:0.1:1, ...
              'LineWidth'   , 2         );
           UtilityLib.print_figure(h,9,7,sprintf('figure/relocations_CDF_compare',...
                nsteps, T,r_sla, r_resource, r_trsh,objective));

            h=figure
            subplot(2, 1, 1);
            plot(sum(U_nfm1>0,1),'r');  hold on;
           % hXLabel=xlabel('Time step'); 
            %hYLabel=ylabel('Active Servers');
            axis([0 nsteps 2 6])
            set( gca                       , ...
                'FontName'   , 'Times New Roman' );
            set([hXLabel, hYLabel], ...
                'FontName'   , 'Times New Roman');
            set([hXLabel, hYLabel]  , ...
                'FontSize'   , 24          );
            set(gca, ...
              'Box'         , 'off'     , ...
              'TickDir'     , 'out'     , ...
              'TickLength'  , [.02 .02] , ...
              'XMinorTick'  , 'on'      , ...
              'YMinorTick'  , 'on'      , ...
              'XGrid'       , 'on'      , ...              
              'YGrid'       , 'on'      , ...
              'XColor'      , [.3 .3 .3], ...
              'YColor'      , [.3 .3 .3], ...
              'XTick'       , 0:20:144, ...
              'LineWidth'   , 2         ,...
              'YTick'       , 0:1:7, ...
              'LineWidth'   , 2         );
            subplot(2, 1, 2);
            plot(sum(U_nfm2>0,1),'--b'); 
            hXLabel=xlabel('Time step'); 
            hYLabel=ylabel('Active Servers');
            axis([0 nsteps 2 6])
            set( gca                       , ...
                'FontName'   , 'Times New Roman' );
            set([hXLabel, hYLabel], ...
                'FontName'   , 'Times New Roman');
            set([hXLabel, hYLabel]  , ...
                'FontSize'   , 24          );
            set(gca, ...
              'Box'         , 'off'     , ...
              'TickDir'     , 'out'     , ...
              'TickLength'  , [.02 .02] , ...
              'XMinorTick'  , 'on'      , ...
              'YMinorTick'  , 'on'      , ...
              'XGrid'       , 'on'      , ...              
              'YGrid'       , 'on'      , ...
              'XColor'      , [.3 .3 .3], ...
              'YColor'      , [.3 .3 .3], ...
              'XTick'       , 0:20:144, ...
              'LineWidth'   , 2         ,...
              'YTick'       , 0:1:7, ...
              'LineWidth'   , 2         );
            UtilityLib.print_figure(h,9,7,sprintf('figure/active_servers_CDF_compare',...
                nsteps, T,r_sla, r_resource, r_trsh,objective));
            
            